---
- name: Example component
  hosts: localhost # On ResearchCloud, the target host is always simply 'localhost'.
  vars:
    alphafold_repo_url: https://github.com/google-deepmind/alphafold3.git
    alphafold_repo_path: /tmp/alphafold
    default_group_name: regular_users
  gather_facts: true

  roles:
    - role: uusrc.general.fact_regular_users
    - role: uusrc.general.fact_workspace_info
    - role: uusrc.general.default_group
      vars:
        default_group_group:
          groupname: "{{ default_group_name }}"
  tasks:
    - name: Obtain alphafold 3 sourcecode
      ansible.builtin.git:
        repo: "{{ alphafold_repo_url }}"
        dest: "{{ alphafold_repo_path }}"

    - name: Ensure that permanent storage is available
      when: fact_workspace_storage | length == 0
      ansible.builtin.fail:
        msg: "No permanent storage found on the workspace! Exiting"

    - name: Set path to databases
      ansible.builtin.set_fact:
        db_path: "{{ fact_workspace_storage[0]['mount'] }}"
    
    - name: Create data directory with setgid
      ansible.builtin.file:
        path: "{{ db_path }}"
        owner: root
        group: "{{ default_group_name }}"
        mode: 02770
        state: directory
        recurse: true

    - name: Run fetch_databases
      ansible.builtin.shell: "bash {{ alphafold_repo_path }}/fetch_databases.sh {{ db_path }}"
