---
collections:
  - name: https://github.com/UtrechtUniversity/researchcloud-items.git # the uusrc.general collection
    type: git
    version: main
  - name: community.docker
roles:
  # - src: geerlingguy.docker
  #   version: 6.1.0
